VERSION:=0.1.0


.PHONY: clean

clean:
	rm -rf api


api: openapi.yaml
	docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local openapitools/openapi-generator-cli:v4.1.3 \
	           generate -i /local/openapi.yaml \
	           --git-user-id rienafairefr \
	           --git-repo-id pybricklink \
			   -p packageName=bricklink \
			   -p packageVersion="$(VERSION)" \
			   -p appDescription="This is pybricklink, an autogenerated package to access Bricklink API" \
			   -p projectName=pybricklink \
	           -g python -o /local/api
