# coding: utf-8

"""
    Bricklink REST API

    Bricklink REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bricklink
from bricklink.api.catalog_api import CatalogApi  # noqa: E501
from bricklink.rest import ApiException


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self):
        self.api = bricklink.api.catalog_api.CatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_items_type_no_get(self):
        """Test case for items_type_no_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
